fixed genus in geospatial ellipse definition
CommonCoreOntology/CommonCoreOntologies pull request #327
Opened 2024-08-05 21:08 UTC by cameronmore

2024-08-06 02:12 UTC, neilotte requested changes
See @alanruttenberg 's shrewd comment an hour ago on the original thread. Looks like there's both a hierarchy issue and a label issue to be addressed here rather than this label update.

2024-08-18 19:18 UTC, neilotte commented
@cameronmore Was my comment here addressed yet?

2024-08-18 19:38 UTC, cameronmore commented
@neilotte yes, and I adjusted a number of other labels and definitions to conform to the correct genus-species. I would recommend looking at via Protege to ensure I did not error.

2024-08-18 20:04 UTC, neilotte approved these changes

2024-08-18 20:04 UTC, merged