changed action regulation to process regulation per #178
CommonCoreOntology/CommonCoreOntologies pull request #437
Opened 2024-08-21 12:19 UTC by cameronmore

2024-09-01 14:02 UTC, neilotte requested changes
@cameronmore It appears 'the label for 'Action Permission' was not updated.

2024-09-01 14:07 UTC, neilotte commented
@cameronmore The definitions of permits, prohibits, requires, and their inverses still reference regulating the involvement of an agent in each process, which means these definitions still are describing acts rather than processes per se. I recommend this language also be removed so that, for instance, mere processes not obviously involving agents as causal actors (e.g. the states of affairs of a cyber system) may be prohibited, permitted, and required.

2024-09-04 14:09 UTC, neilotte requested changes

2024-09-04 14:09 UTC, neilotte commented on src/cco-extensions/ModalRelationOntology.ttl
>                      cco:is_curated_in_ontology <http://www.ontologyrepository.com/CommonCoreOntologies/Mid/ModalRelationOntology> ;
@cameronmore 'region' has a mispelling. 

Also, what do you think of: "y is_permitted_by x at t iff: x is an instance of Process Regulation at time t, and y is an instance of Process at time t, and x prescribes that y may occur." 

If acceptable, this phrasing would apply to multiple object properties in this PR.

2024-09-04 15:18 UTC, mark-jensen commented
@cameronmore MRO is built automatically as part of the release process. There is no need to make changes manually, unless you can guarantee that every change to any property in CCO from v1.5 to v1.6 is accounted for.

2024-09-11 17:24 UTC, mark-jensen approved these changes

2024-09-11 17:24 UTC, APCox approved these changes

2024-09-11 17:25 UTC, neilotte approved these changes

2024-09-11 17:25 UTC, merged