Version 1.6
CommonCoreOntology/CommonCoreOntologies pull request #481
Opened 2024-09-15 17:42 UTC by mark-jensen

2024-09-15 17:50 UTC, mark-jensen commented
@neilotte @johnbeve @APCox The only surprise is that I relabeled "Merged All Core" to "Common Core Ontologies Merged" and removed the date in the .ttl filename. 

I think something like this makes more sense than our previous way of doing it. I did not change the ontology IRI since I don't want to cause too much unnecessary churn before the full IRI update to come.

2024-09-27 01:11 UTC, johnbeve requested changes

2024-09-27 01:11 UTC, johnbeve commented on documentation/diff-reports-previous-version/AgentOntology.md
> +- [Domain of a Country](http://www.ontologyrepository.com/CommonCoreOntologies/Country) [editorialNote](http://www.w3.org/2004/02/skos/core#editorialNote) "'Country' is an unclear term. Does it refer
The addition correctly replaces "county" with "country" but both include "definine" instead of "define" in the last sentence.

2024-09-27 01:15 UTC, johnbeve commented on documentation/diff-reports-previous-version/AgentOntology.md
> +- [prohibits](http://www.ontologyrepository.com/CommonCoreOntologies/prohibits) [definition](http://www.ontologyrepository.com/CommonCoreOntologies/definition) "x prohibits y at t iff: x is an instan
I believe "x prescribes that some that y must not occur" should be "x prescribes that some y must not occur"

2024-09-27 01:16 UTC, johnbeve commented on documentation/diff-reports-previous-version/AgentOntology.md
> +- [requires](http://www.ontologyrepository.com/CommonCoreOntologies/requires) [definition](http://www.ontologyrepository.com/CommonCoreOntologies/definition) "x requires y at t iff: x is an instance
I believe "x prescribes that some that y must occur" should be "x prescribes that some y must occur"

2024-09-27 01:31 UTC, johnbeve commented on documentation/diff-reports-previous-version/GeospatialOntology.md
> +#### Added
I can't find the PR or commit where this was updated. I'm not sure why "that is" was added. The original definition seems appropriate and the replacement seems awkward.

2024-09-27 01:33 UTC, johnbeve commented on documentation/diff-reports-previous-version/InformationEntityOntology.md
> +- [International Geomagnetic Reference Field](http://www.ontologyrepository.com/CommonCoreOntologies/InternationalGeomagneticReferenceField) [comment](http://www.w3.org/2000/01/rdf-schema#comment) "T
There are two spaces between "for" and "navigational"

2024-09-27 01:36 UTC, johnbeve requested changes
Please see comments throughout

2024-09-27 02:40 UTC, johnbeve commented
Happy to approve even without the changes, just want to note them so we can update develop before the next release. 
Thanks @mark-jensen!

2024-09-27 02:41 UTC, johnbeve approved these changes

2024-09-27 02:58 UTC, merged